version: "3.1"

services:

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: vitta-assessment-frontend-node
    working_dir: /application
    volumes:
      - .:/application
      - /application/node_modules
    command: npm run dev
    ports:
      - 8010:8010
