version: '2'
services:
  api:
    build: ./api
    ports:
     - "8888:8888"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./api:/app
  db:
    build: ./database
    ports:
     - "3306:3306"
    restart: always