version: '3'
services:
  api:
    build: ./api
    ports:
     - "4200:4200"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./api:/src
  db:
    build: ./database
    ports:
     - "3306:3306"
    restart: always