version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    command: bash -c "chmod +x appinit.sh ; ./appinit.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

