version: '2'
services:
  api:
    build: ./api
    ports:
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    volumes:
     - ./api:/app
  db:
    build: ./database
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  front:
    build: ./front
    ports:
     - "8080:80"
    depends_on:
     - api
    restart: always
